name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Download Go modules
        run: go mod tidy

      - name: Run Go tests
        run: go test ./... -v

      - name: Install golangci-lint
        run: curl -sSfL [https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh](https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh) | sh -s -- -b $(go env GOPATH)/bin v1.58.1

      - name: Run golangci-lint
        run: $(go env GOPATH)/bin/golangci-lint run ./...